development:
  css_file_name: operator.css
  html_file_name: operator.html.erb
  option_to_store_email: csv
  campaign_monitor_api_key:
  campaign_monitor_list_id:
  mail_chimp_api_key:
  mail_chimp_list_id:
  csv_file_name: ../signups/data.csv
  launching_date: July 9, 2020 00:00:00

test:
  css_file_name: operator.css
  html_file_name: operator.html.erb
  option_to_store_email: csv
  campaign_monitor_api_key:
  campaign_monitor_list_id:
  mail_chimp_api_key:
  mail_chimp_list_id:
  csv_file_name: ../signups/data.csv
  launching_date: July 9, 2020 00:00:00

production:
  css_file_name: operator.css
  html_file_name: operator.html.erb
  option_to_store_email: csv
  campaign_monitor_api_key:
  campaign_monitor_list_id:
  mail_chimp_api_key:
  mail_chimp_list_id:
  csv_file_name: ../signups/data.csv
  launching_date: July 9, 2020 00:00:00
